# Cloudflare Pages configuration

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[env.production]
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCZAmGriqlYJL_RLvRx7iKGQz7pbY2nrB0"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "jacob-barkin-website.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "jacob-barkin-website"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "jacob-barkin-website.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "1093183769646"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:1093183769646:web:0fbbcd20023cb9ec8823bf"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-KTBS67S2PC"
