name: Deploy Appwrite Functions

on:
  push:
    branches:
      - modern-redesign-shadcn
    paths:
      - 'functions/email-notification/**'
      - 'functions/email-notification-updated/**'
      - '.github/workflows/appwrite-deploy.yml'
  workflow_dispatch:

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    outputs:
      secrets_exist: ${{ steps.check.outputs.secrets_exist }}
    steps:
      - id: check
        run: |
          if [[ -n "${{ secrets.APPWRITE_EMAIL }}" && -n "${{ secrets.APPWRITE_PASSWORD }}" && -n "${{ secrets.APPWRITE_PROJECT_ID }}" && -n "${{ secrets.APPWRITE_EMAIL_FUNCTION_ID }}" ]]; then
            echo "secrets_exist=true" >> $GITHUB_OUTPUT
          else
            echo "secrets_exist=false" >> $GITHUB_OUTPUT
            echo "::warning::One or more required Appwrite secrets are not set. Skipping deployment."
          fi

  deploy_appwrite_functions:
    needs: check_secrets
    if: needs.check_secrets.outputs.secrets_exist == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Appwrite CLI
        run: npm install -g appwrite-cli

      - name: Login to Appwrite
        run: |
          echo 'y' | appwrite login --email ${{ secrets.APPWRITE_EMAIL }} --password ${{ secrets.APPWRITE_PASSWORD }}
          appwrite client --project-id ${{ secrets.APPWRITE_PROJECT_ID }}

      - name: Deploy Email Notification Function
        run: |
          cd functions/email-notification-updated
          appwrite functions create-deployment \
            --function-id ${{ secrets.APPWRITE_EMAIL_FUNCTION_ID }} \
            --entrypoint src/main.js \
            --code . \
            --activate true

  build_function:
    runs-on: ubuntu-latest
    if: needs.check_secrets.outputs.secrets_exist != 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: functions/email-notification-updated
        run: npm ci

      - name: Test function build
        working-directory: functions/email-notification-updated
        run: |
          echo "Building function to verify it compiles correctly"
          npm install
          echo "Function build successful"
